### PR TITLE
fix gpu isosurface group id

### LINKED ISSUE #331: Clicking on surfaces from volume streaming does not correctly center
Clicking on isosurfaces from volume streaming does not correctly center them. The center/zoom on click works fine for isosurfaces from volumes not loaded using the streaming behavior.

### PR DESCRIPTION
**Pull request by arose**
Isosurface group id from GPU MC was wrong for axis order other than 012. Fixes #331.

Generally it would probably be better to handle axis order from the start when doing gpu mc which would also simplify data upload to the gpu a bit. Another time.

### CODE REVIEW

File: src/mol-gl/compute/marching-cubes/isosurface.ts [hunk 1]
```diff
@@ -115,7 +118,7 @@ function setRenderingDefaults(ctx: WebGLContext) {
     state.clearColor(0, 0, 0, 0);
 }
 
-export function createIsosurfaceBuffers(ctx: WebGLContext, activeVoxelsBase: Texture, volumeData: Texture, histogramPyramid: HistogramPyramid, gridDim: Vec3, gridTexDim: Vec3, transform: Mat4, isoValue: number, invert: boolean, packedGroup: boolean, vertexTexture?: Texture, groupTexture?: Texture, normalTexture?: Texture) {
+export function createIsosurfaceBuffers(ctx: WebGLContext, activeVoxelsBase: Texture, volumeData: Texture, histogramPyramid: HistogramPyramid, gridDim: Vec3, gridTexDim: Vec3, transform: Mat4, isoValue: number, invert: boolean, packedGroup: boolean, axisOrder: Vec3, vertexTexture?: Texture, groupTexture?: Texture, normalTexture?: Texture) {
```
Comment (dsehnal) [inline src/mol-gl/compute/marching-cubes/isosurface.ts:121]: The saga continues :)

**Review by dsehnal — APPROVED** [review]
